### ISSUE TITLE
I can't find the `format` function in index.js - solution: republish latest to npm?

### ISSUE THREAD

**Issue by elsigh** [gilyes/chordprojs#3]
Neither can babel ;)

**Comment by gilyes** [comment]
Not sure where are you looking but it's in chordpro.js...

**Comment by elsigh** [comment]
huh, somehow I did an install and ended up with version 0.1.1!

**Comment by elsigh** [comment]
oh, looking on npm: https://www.npmjs.com/package/chordprojs

0.1.1 is the latest published version

**Comment by gilyes** [comment]
That's a different library with the same name: https://github.com/tvdavies/chordprojs
This one is not on npm.

**Comment by elsigh** [comment]
Whoah, ok - that's unfortunate! I wonder if it might be worth picking a unique package name as a solution - plus.. it would be so great to have on npm! (nudge)
